### ISSUE TITLE
Azure Functions endpoint not serving API

### ISSUE THREAD

**Issue by adityaviswanathan** [RadientBrain/mando-extractor#2]
Upon successfully deploying the app with `terraform apply -var azure_client_id=...`, there is no available FastAPI Swagger endpoint at `/docs` to access the API [as there should be](https://dev.to/manukanne/azure-functions-and-fastapi-14b6):

<img width="500" alt="Screenshot 2023-10-30 at 11 28 23 AM" src="https://github.com/RadientBrain/mando-extractor/assets/3068877/15ff27bc-cbbf-42f8-a38c-33f74ab8129e">

<img width="500" alt="Screenshot 2023-10-30 at 11 34 33 AM" src="https://github.com/RadientBrain/mando-extractor/assets/3068877/b12bedfc-9a5f-47fb-87bd-acc19df1e9e9">

See a comparable Azure Functions app that shows a `http_app_func` endpoint in Azure portal

<img width="500" alt="Screenshot 2023-10-30 at 11 29 00 AM" src="https://github.com/RadientBrain/mando-extractor/assets/3068877/a1e75095-3968-4770-80de-cbee501eda78">

and serves the API as expected at `...azurewebsites.net/docs`:

<img width="500" alt="Screenshot 2023-10-30 at 11 34 48 AM" src="https://github.com/RadientBrain/mando-extractor/assets/3068877/a44005c1-94fc-4c11-9b55-40e467e16ac0">

Unfortunately this API is unusable as is when deployed through Azure Functions.

**Comment by RadientBrain** [comment]
Hey @adityaviswanathan please check again.

**Comment by adityaviswanathan** [comment]
Are you testing this on your end? This is still not working:

<img width="1440" alt="Screenshot 2023-10-31 at 11 46 31 AM" src="https://github.com/RadientBrain/mando-extractor/assets/3068877/33e0a638-3f43-46ed-afe7-8e5aa246fa27">

When I go to the [API URL](https://extractorlinuxfunctionapp.azurewebsites.net/docs), I get a `404` and still don't see the Swagger docs:

<img width="1440" alt="Screenshot 2023-10-31 at 11 48 19 AM" src="https://github.com/RadientBrain/mando-extractor/assets/3068877/4a213189-f94c-4204-a79b-0f6295492762">

**Comment by RadientBrain** [comment]
Hey @adityaviswanathan I have pushed the changes for this azure, the extractor basically works on local machine, the only issue is the hosting part on azure, I have checked the blogpost that you mentioned, and have updated the code according to this, I hope this should work, let me know if the /docs is still not being hosted properly.

**Comment by adityaviswanathan** [comment]
@RadientBrain different error, but still not working:

<img width="1440" alt="Screenshot 2023-10-31 at 2 10 40 PM" src="https://github.com/RadientBrain/mando-extractor/assets/3068877/2c5eb361-1c60-4f8f-b864-66653d209ea2">

and not seeing the expected `http_app_func` in the Azure portal:

<img width="1440" alt="Screenshot 2023-10-31 at 2 12 26 PM" src="https://github.com/RadientBrain/mando-extractor/assets/3068877/e1e3d37e-2494-413b-a654-7f9dad89ca46">

**Comment by RadientBrain** [comment]
Hey @adityaviswanathan see screenshots this is working:-

Terminal:
<img width="732" alt="image" src="https://github.com/RadientBrain/mando-extractor/assets/54241703/f480fdec-06e7-42e2-b2e2-0c370fac054b">

The root route:
<img width="463" alt="image" src="https://github.com/RadientBrain/mando-extractor/assets/54241703/4029e51c-9c3c-440b-b604-5bc50a5a7e8b">

The docs route:
<img width="1287" alt="image" src="https://github.com/RadientBrain/mando-extractor/assets/54241703/ed362488-a222-489b-a8a8-c523b877cff6">

The extract route (website):
<img width="1022" alt="image" src="https://github.com/RadientBrain/mando-extractor/assets/54241703/0dfe1b19-7a8f-4292-9121-f9218189894f">

The extract route (pdf):
<img width="950" alt="image" src="https://github.com/RadientBrain/mando-extractor/assets/54241703/f72b2feb-e0e6-40a3-82f3-bc118a7cd3d0">

**Comment by adityaviswanathan** [comment]
@RadientBrain perhaps it works locally, but it does not deploy to Azure. See my lingering issue:

![Uploading Screenshot 2023-11-01 at 9.38.27 AM.png…]()

**Comment by RadientBrain** [comment]
Hey @adityaviswanathan can't see your screenshot

**Comment by RadientBrain** [comment]
Updated terraform for in [97ecd98](https://github.com/RadientBrain/mando-extractor/commit/97ecd983604c9ce080321b5afbeba92f8c08e15d) to automate packaging and uploading.


Try these commands:

1. **Initialize Terraform**: This will download the necessary provider plugins.

    ```bash
    terraform init
    ```

2. **Validate the Terraform configuration**: This will check the syntax of your `infra.tf` file.

    ```bash
    terraform validate
    ```

3. **Generate and review an execution plan**: This will show you what changes Terraform will make to your infrastructure.

    ```bash
    terraform plan
    ```

4. **Apply the Terraform configuration**: This will apply the changes required to reach the desired state of the configuration.

    ```bash
    terraform apply
    ```

    You will be asked to confirm that you want to apply the changes. Type `yes` and press `Enter` to confirm.

Please note that you need to have Terraform installed on your machine to run these commands. Also, you need to be logged in to your Azure account (you can do this by running `az login`).
